name: productivity_agent
description: AI Productivity Agent for RUET EEE Student

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  flutter_slidable: ^3.1.0
  # State management
  provider: ^6.1.2
  # Local storage
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.4
  path: ^1.9.0
  shared_preferences: ^2.3.1
  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  # Networking
  http: ^1.2.2
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.2
  sqflite_common_ffi_web: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
